### ISSUE TITLE
When Inspeqtor doesn't understand its on own conf file it simply doesn't start - no error message

### ISSUE THREAD

**Issue by fuzzygroup** [mperham/inspeqtor#131]
Hi Mike, 

Happy Thanksgiving!  I had this configuration

send alerts via email with
  smtp_server localhost,
  to_email fuzzygroup@gmail.com,curry.pelot@fi-navigator.com,scott.johnson@fi-navigator.com,
  from_email fidb-i-0667cfb2e7cde5633@ip-172-31-43-176

(at the end of an otherwise normal conf file).  The change was I added two additional email addresses:

curry.pelot@fi-navigator.com,scott.johnson@fi-navigator.com,

And that caused inspeqtor NOT to start.  Maybe my syntax was wrong but shouldn't there be an error message instead of silently dying?

Thanks!

**Comment by mperham** [comment]
There should be an error message rather than silent death.  Possibly a bug in the parser, which is generated by gocc here:

https://github.com/mperham/inspeqtor/blob/master/Makefile#L43
https://github.com/goccmack/gocc

Looks like gocc has had a bunch of fixes in the last two years and they might have fixed this.
