### ISSUE TITLE
Init.d service in down state not restarted

### ISSUE THREAD

**Issue by felixbuenemann** [mperham/inspeqtor#72]
I'm monitoring a couple of init.d based services, example:

```
check service thin-faye-staging-0
  if memory:rss > 80m for 8 cycles then restart
  if cpu:user > 10% for 16 cycles then alert
  if cpu:user > 95% for 16 cycles then restart
```

If I kill the process for that service, inspeqtor 0.7.0-2 detects it as down and sends an email alert, but it does not restart the service.

**Comment by felixbuenemann** [comment]
@mperham I understand your point. However Inspeqtor already supports restarting services, so as long as the init system is used to start a service that is down there should be no huge changes required.

The DSL could be something like:

```
check service foo
  if down then start
```

**Comment by mperham** [comment]
The issue is that smart inits themselves have a restart policy, e.g. see systemd's [Restart variables](http://0pointer.de/public/systemd-man/systemd.service.html) in use [here](https://github.com/mperham/inspeqtor/blob/master/packaging/root/usr/share/inspeqtor/systemd/inspeqtor.service#L23).  Inspeqtor will tell you if the service is down.  If the init can't bring it up, there's no reason to think Inspeqtor can.
